- name: java-starter-guides playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openshift_user:
    openshift_password:
    openshift_token:
    openshift_master_url:
    openshift_user_password:
    user_count:
    workshop_type:

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules
  - role: common-definitions
  # Input:
  #     openshift_user
  #     openshift_password
  #     openshift_token
  # Output:
  #     apps_hostname_suffix
  - role: deprovision-java-starter-guides
    playbook_debug: false