kind: Template
apiVersion: v1
metadata:
  name: guide
  annotations:
    description: Template to deploy a workshop guide with workshopper. Look into any of the workshops for the used variables that can be defined in the configMap.
parameters:
- name: CONTENT_URL_PREFIX
  description: Console url (e.g. https://raw.githubusercontent.com/openshift-labs/starter-guides/39)
  value: https://raw.githubusercontent.com/jorgemoralespou/java-starter-guides/master
  displayName: Content URL prefix
  required: true
- name: WORKSHOPS_URLS
  description: Workshop definition url (e.g. https://raw.githubusercontent.com/openshift-labs/starter-guides/39/_workshops/training.yml)
  value: file:///workshop/workshop.yml
  displayName: Workshop Url
  required: true
- name: CONSOLE_ADDRESS
  description: Console url (e.g. master.mycluster.openshiftworkshop.com or console.mycluster.gce.pixy.io:8443)
  value:
  displayName: Console url
  required: true
- name: ROUTER_ADDRESS
  description: Application subdomain (e.g. apps.mycluster.openshiftworkshop.com or apps.mycluster.gce.pixy.io)
  value:
  displayName: Application subdomain
  required: true
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: guides
    labels:
      app: guides
      role: config
  data:
    WORKSHOPS_URLS: ${WORKSHOPS_URLS}
    workshop.yml: |+
      ---
      id: workshop
      name: Developing Java Applications on OpenShift - Starter Lab

      content:
        url: ${CONTENT_URL_PREFIX}

      vars:
        CONSOLE_ADDRESS: ${CONSOLE_ADDRESS}
        ROUTER_ADDRESS: ${ROUTER_ADDRESS}


      modules:
        activate:
        - common-environment
        - common-cli
        - common-explore
        - common-parksmap-architecture
        - parksmap-docker
        - parksmap-scaling
        - parksmap-routes
        - parksmap-logging
        - parksmap-permissions
        - parksmap-rsh
        - nationalparks-java
        - nationalparks-databases
        - nationalparks-application-health
        - nationalparks-codechanges-gogs
        - mlbparks-templates
        - mlbparks-clustering
        - mlbparks-binary-build
        - mlbparks-debugging
        - common-further-resources
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: workshopper
    labels:
      app: guides
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: osevg/workshopper:latest
      importPolicy: {}
      referencePolicy:
        type: Source
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: guides
    labels:
      app: guides
  spec:
    replicas: 1
    selector:
      app: guides
      deploymentconfig: guides
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: guides
          deploymentconfig: guides
      spec:
        containers:
        - image: workshopper
          envFrom:
            - configMapRef:
                name: guides
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: guides
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /workshop
            name: volume-config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: guides
          name: volume-config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - guides
        from:
          kind: ImageStreamTag
          name: workshopper:latest
      type: ImageChange
- kind: Service
  apiVersion: v1
  metadata:
    name: guides
    labels:
      app: guides
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: guides
      deploymentconfig: guides
    sessionAffinity: None
    type: ClusterIP
- kind: Route
  apiVersion: v1
  metadata:
    name: guides
    labels:
      app: guides
  spec:
    host:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: guides
      weight: 100
    wildcardPolicy: None
